included:
  - Sources
excluded:
  - Tests
  - SampleApp
  - Package.swift
  - Dangerfile.swift
  - DangerfileExtensions
allow_zero_lintable_files: true
opt_in_rules:
  - all
disabled_rules:
  - conditional_returns_on_newline
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_self
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - force_unwrapping
  - function_default_parameter_at_end
  - indentation_width #Ref: https://github.com/realm/SwiftLint/issues/3046
  - missing_docs
  - multiline_arguments_brackets
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - object_literal
  - prefer_nimble
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - required_deinit
  - return_value_from_void_function
  - sorted_enum_cases
  - switch_case_on_newline
  # - unowned_variable_capture
  # - unused_optional_binding
  # - vertical_parameter_alignment_on_call # False positive with Multiple trailing closures
  - vertical_whitespace_between_cases
  # - void_function_in_ternary
cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  ignore_comment_only_lines: true
# indentation_width:
#   include_comments: false # Ref: https://github.com/realm/SwiftLint/issues/3046
identifier_name:
  min_length:
    warning: 2
    error: 1
large_tuple:
  warning: 3
  error: 4
line_length:
  warning: 180
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
nesting:
  type_level: 3
trailing_closure:
  only_single_muted_parameter: true
